### ISSUE TITLE
Overall script runtime is usually more than a minute on local testbed

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi-ixnetwork#197]
- @ashutshkumr to provide basic API perf CSV to start investigating areas
- @alakendu to investigate and evaluate opportunities to speed things up in a given area

**Comment by ashutshkumr** [comment]
Script and perf data posted in https://github.com/open-traffic-generator/ixnetwork/pull/198

**Comment by alakendu** [comment]
We did some optimization in traffic where we found lots of improvement (CICD run drop from 50min to 25min).

We will revisit device optimization after finalize model change

**Comment by ANISH-GOTTAPU** [comment]
stale issue
