### ISSUE TITLE
IxNetwork Issue: starting a fixed packet flow doesn't stop until stopped manually

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/snappi-ixnetwork#229]
Steps:
1. Created 2 ipv4 flows (block traffic) with fixed packet count.
2. started one flow and could see received packets at Rx @ 0% loss.
3. GUI still shows the traffic in running state until the traffic is stopped manually.

This issue is created just to track as this is related to IxNetwork.

**Comment by alakendu** [comment]
please attached that script

**Comment by alakendu** [comment]
I am not getting this issue in IxNetwork-9.10 at the testing script https://github.com/open-traffic-generator/ixnetwork/blob/master/tests/traffic/test_ip_device_and_flow.py
Could you please double check

![image](https://user-images.githubusercontent.com/35574510/104454746-5274ae80-55cc-11eb-8a6c-38181d47ecae.png)

**Comment by ashutshkumr** [comment]
I just checked, this is reproducible only against 9.10 IxN docker image (and not 9.10 IxN Win API Server). We probably should report to traffic team after some more investigation.

@ajbalogh FYI

**Comment by Rangababu-R** [comment]
@alakendu @ashutshkumr 
I am able to reproduce it in windows API server. This is reproduced manually.
Steps:
1. Ran the script which creates 2 traffic items (fixed).
2. Start the traffic and it stops after the fixed packet count is transmitted.
3. Then start one traffic item alone manually.
4. Now we can see on GUI the fixed packets are transmitted but the traffic item will not get stopped.

This issue was found while I was debugging the script issue.

![image](https://user-images.githubusercontent.com/72373312/104982485-ca116600-5a30-11eb-842a-088800e035c3.png)

**Comment by alakendu** [comment]
Issue should not present in v0.4.11
