### ISSUE TITLE
Add a test script to validate https://github.com/open-traffic-generator/ixnetwork/pull/238

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi-ixnetwork#239]

**Comment by Rangababu-R** [comment]
pull request: #238 

This fix will return RequestDetail object for set_state. So the code looks like:
config_state = control.ConfigState(config=config, state='set')
result = api.set_state(control.State(config_state))
print(result.errors)
print(result.warnings)

Please review and let me know if this will fulfill the requirement.

result.errors is no more valid and we raise snappiException.
there is a testcase for snappiException.
