### ISSUE TITLE
Traffic apply error if flow is configured with only tx port instead of tx&rx ports

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#240]
Traffic apply error if flow is configured with `only tx port` instead of `tx&rx ports`

**Comment by ashutshkumr** [comment]
Implemention should be as such that tx port shouldn't receive back packets it sent out (no self-destined or loopback impl)

**Comment by alakendu** [comment]
Issue should not present in v0.4.11
