### ISSUE TITLE
Snappi: Need to implement link state up/down 

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#248]
`Link State` model implementation in concrete

**Comment by ashutshkumr** [comment]
@Rangababu-R please check and TC if missing

**Comment by alakendu** [comment]
@Rangababu-R IxNetwork concreate has set_link_state support. Please validate and add test case accordingly.

**Comment by alakendu** [comment]
Issue should not present in v0.4.11
