### ISSUE TITLE
Latency and timestamp are not being returned by get_flow_results API

### ISSUE THREAD

**Issue by danmih-ixia** [open-traffic-generator/snappi-ixnetwork#253]
**ixn_api.get_flow_results(result.FlowRequest())** returns following columns:
> name transmit    port_tx    port_rx  frames_tx  frames_rx  frames_tx_rate  frames_rx_rate  bytes_tx  bytes_rx  loss  bytes_tx_rate  bytes_rx_rate
Latencies, timestamps and others are not being returned.

**Comment by ashutshkumr** [comment]
Might need model changes for timestamp. Will need to create a separate issue for that.

**Comment by alakendu** [comment]
fix should available in latest snappi build (v0.4.27). Please check model as several change happened in past.
