### ISSUE TITLE
Implement : Fetch Protocol session stat ( IP UP or DOWN ) so that this can be logged to user.

### ISSUE THREAD

**Issue by SubhajitPalKeysight** [open-traffic-generator/snappi-ixnetwork#29]
ixnetwork.StartAllProtocols(Arg1='sync')

protocolSummary = session.StatViewAssistant('Protocols Summary')
    protocolSummary.CheckCondition('Sessions Not Started', protocolSummary.EQUAL, 0)
    protocolSummary.CheckCondition('Sessions Down', protocolSummary.EQUAL, 0)
    logger.info(protocolSummary)

**Comment by ANISH-GOTTAPU** [comment]
Protocol sessions for individual protocol BGP is added and closing the issue
