### ISSUE TITLE
Escape special regex chars seen in snappi object names (main branch)

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi-ixnetwork#304]
Issue originated from https://github.com/open-traffic-generator/ixnetwork/issues/297

**Comment by ashutshkumr** [comment]
Need to check what object it applies to. Currently only implemented for flows. Check if we can do the same for all objects during validation itself.

**Comment by alakendu** [comment]
All regex are replace with generalize string
