### ISSUE TITLE
Resolve intermittent BGP TC failure

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi-ixnetwork#335]
https://github.com/open-traffic-generator/ixnetwork/runs/2285750072?check_suite_focus=true

**Comment by alakendu** [comment]
@Rangababu-R please double check. Because sometime we are getting this issue.

**Comment by Rangababu-R** [comment]
This issue is resolved with latest modification by Anish. which is available in snappi-ixnetwork version 0.4.11
