### ISSUE TITLE
event enable should enable all events as per the model

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#363]
event enable should enable all events as per the model, but `rx_rate_threshold` needs to be enabled for dataplane convergence
```
    config.advanced.event.enable = True
    config.advanced.event.rx_rate_threshold.enable = True
    config.advanced.event.rx_rate_threshold.threshold = 90

    config.advanced.convergence.enable = True
```

script:
https://github.com/open-traffic-generator/snappi-tests/pull/15

**Comment by alakendu** [comment]
@ANISH-GOTTAPU could you please double check

**Comment by ANISH-GOTTAPU** [comment]
Done
