### ISSUE TITLE
convergence time is returned in microsecond, but the model has mentioned it as nanoseconds

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#364]
Need to convert `microseconds` to `nanoseconds` and return it

(Pdb) print(analytics)
- convergence:
    control_plane_data_plane_convergence_ns: 1366277.0
    data_plane_convergence_ns: 0
    events:
    - begin_timestamp_ns: 939000
      end_timestamp_ns: 939000
      source: rx1_rr
      type: route_withdraw
    service_interruption_time_ns: 0.0
  name: convergence_test

![image](https://user-images.githubusercontent.com/48308607/117917155-1c3f0580-b306-11eb-820d-ad40fbb3544d.png)

**Comment by alakendu** [comment]
Issue should not present in v0.4.11
