### ISSUE TITLE
Flow_Metrics: first_timestamp and last_timestamp returns null

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#373]
f1.metrics.timestamps = True

return:
flow_metrics:
- bytes_rx: 612279296
  bytes_tx: 0
  frames_rx: 597929
  frames_rx_rate: 59866.0
  frames_tx: 597930
  frames_tx_rate: 59866.0
  loss: 0.0
  name: f1
  port_rx: rx
  port_tx: tx
  timestamps:
    first_timestamp_ns: null
    last_timestamp_ns: null
  transmit: started

**Comment by alakendu** [comment]
Issue should not present in latest snappi_ixnetwork (v0.4.11)
