### ISSUE TITLE
Flow Metrics: Link state and withdraw events are not working without events notification enable

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#374]
As per the model, the description says events enable True is _to enable **notifications**_ . If user doesn't want notification he can still go and Link state down or withdraw event. This is my understanding, we can discuss and close it

![image](https://user-images.githubusercontent.com/48308607/120271812-a0fbbe80-c2c9-11eb-92bf-9ad43214ee76.png)

config.events.enable = True

link_state = api.link_state()
link_state.state = link_state.DOWN
link_state.port_names = ['rx']
api.set_link_state(link_state)

**Comment by alakendu** [comment]
Issue should not present in latest snappi_ixnetwork (v0.4.11)
