### ISSUE TITLE
Flow_Metrics: Latency timestamps returns null

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#375]
flow_metrics:
- bytes_rx: 761697280
  bytes_tx: 0
  frames_rx: 743845
  frames_rx_rate: 0.0
  frames_tx: 743845
  frames_tx_rate: 0.0
  latency:
    **average_ns: null
    maximum_ns: null
    minimum_ns: null**
  loss: 0.0
  name: f1
  port_rx: rx
  port_tx: tx
  transmit: stopped

**Comment by alakendu** [comment]
Please validate in latest fix

**Comment by ANISH-GOTTAPU** [comment]
still getting null value with latest pull on the branch

flow_metrics:
- bytes_rx: 102400
  bytes_tx: 0
  frames_rx: 100
  frames_rx_rate: 0.0
  frames_tx: 100
  frames_tx_rate: 0.0
  latency:
    average_ns: null
    maximum_ns: null
    minimum_ns: null
  loss: 0.0
  name: f1
  port_rx: rx
  port_tx: tx
  transmit: stopped

**Comment by alakendu** [comment]
hopefully this should fix in https://github.com/open-traffic-generator/ixnetwork/commit/716120615390516502145fd2d0afd41c2614e276
Please validate

**Comment by alakendu** [comment]
Issue should not present in latest snappi_ixnetwork (v0.4.11)
