### ISSUE TITLE
[LAG]: Unable to get CP/DP Convergence time for LAG with snappi

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#415]
When we do a link flap or a route withdraw operation with LAG ports ,Though I see the CP/DP value under user defined statistics,  the event name is empty under flow statistics and I am getting the below exception for the below snippet

request = cvg_api.convergence_request()
request.convergence.flow_names = []
**convergence_metrics = cvg_api.get_results(request).flow_convergence**

>           raise SnappiIxnException(err)
E           SnappiIxnException:   File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 146, in get_results
E               response = self._result(payload.convergence)
E             File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 206, in _result
E               flow_rows = self._get_flow_rows(flow_names)
E             File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 358, in _get_flow_rows
E               raise Exception("Somehow event is not reflected in stat")
E            Somehow event is not reflected in stat

cvg_req    = <snappi_convergence.snappi_convergence.ConvergenceRequest object at 0x7fc815bfcad0>
cvg_res    = <snappi_convergence.snappi_convergence.ConvergenceResponse object at 0x7fc815bfcb90>
err        = Exception('Somehow event is not reflected in stat',)
payload    = <snappi_convergence.snappi_convergence.ConvergenceRequest object at 0x7fc815bfcd70>
self       = <snappi_ixnetwork.snappi_convergence_api.Api object at 0x7fc8161ff8d0>

**Comment by selldinesh** [comment]
FYI: When i do the drill down of the LAG ports with physical ports i see the event name

**Comment by ANISH-GOTTAPU** [comment]
As discussed, event for route link down in populated but route withdraw is not populated on LAG ports. Please check and revert

**Comment by ANISH-GOTTAPU** [comment]
Hi @selldinesh, as discussed we will provide the fix from Snappi once we are able to see the route withdraw event for LAG ports after the hotfix from ixNetwork end

**Comment by selldinesh** [comment]
As discuss , have provided the patch for 9.10 version which shows the verbose on the Event Name column

**Comment by ANISH-GOTTAPU** [comment]
Hi @selldinesh, We have discussed internally and the verbose doesn't make sense and we are looking for actual event name
![image](https://user-images.githubusercontent.com/48308607/127808303-21fcb195-1bd6-4a0a-8fb4-18d8d917fe6c.png)
