### ISSUE TITLE
Need support to select the mesh type for source/Dest Mesh and as well as for Route Mesh

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#427]
We must be able to select the mesh type for Src/Dest Mesh and for Route Mesh
options: one-one, many-many, fully meshed

**Comment by Rangababu-R** [comment]
@selldinesh this feature is already supported
flows.flow()[-1].tx_rx.device.mode
supports "one_to_one" and "mesh"
defaults to mesh
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/open-traffic-generator/models/master/artifacts/openapi.yaml#operation/set_config

**Comment by ANISH-GOTTAPU** [comment]
stale issue
