### ISSUE TITLE
Unable to fetch dp/dp stats for reboot cases

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#432]
The below snippet is not working

    request = cvg_api.convergence_request()
    request.convergence.flow_names = ['IPv4 1-IPv4 2','IPv6 2-IPv6 1','IPv4 1-Network Group 1','Network Group 2-IPv6 2','Network Group 1-IPv4 1']
    convergence_metrics = cvg_api.get_results(request).flow_convergence
    for metrics in convergence_metrics:
        logger.info('DP/DP Convergence Time (ms): {}'.format(metrics.data_plane_data_plane_convergence_us/1000))

Its expecting an event name for the convergence stats, since the event is triggered from the dut side its not populated in flow stats. So we need a way to get the dp/dp stats even without the event name, since the stats can be seen with drill down of traffic item

**Comment by ANISH-GOTTAPU** [comment]
addressed in snappi[ixnetwork]==0.5.3
