### ISSUE TITLE
Timeout for convergence stats is taking too long ( approx 5 mins )

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#440]
def _get_flow_rows(self, flow_names):
        count = 0
        sleep_time = 0.5
        flow_stat = self._api.assistant.StatViewAssistant("Flow Statistics")
        if "Show Physical Ports in LAG" in flow_stat.DrillDownOptions():
            flow_index = {}
            drill_down_option = "Show Physical Ports in LAG"
            for index, row in enumerate(
                self._get_traffic_rows(flow_stat, drill_down_option)
            ):
                flow_index[row["Traffic Item"]] = index
            drill_down_options = flow_stat.DrillDownOptions()
            drilldown_index = drill_down_options.index(drill_down_option)
            flow_stat.Drilldown(
                0,
                drill_down_option,
                flow_stat.TargetRowFilters()[drilldown_index],
            )
            flow_stat = self._api.assistant.StatViewAssistant(
                "Flow Statistics"
            )
        has_flow = False
        while True:
            self._api.info("Count %d"%count)

06:40:34 connection._info L0250 INFO | [ixn-otg] Count 0
06:40:47 connection._info L0250 INFO | [ixn-otg] Count 1
06:40:59 connection._info L0250 INFO | [ixn-otg] Count 2
06:41:12 connection._info L0250 INFO | [ixn-otg] Count 3
06:41:25 connection._info L0250 INFO | [ixn-otg] Count 4
06:41:37 connection._info L0250 INFO | [ixn-otg] Count 5
06:41:50 connection._info L0250 INFO | [ixn-otg] Count 6
06:42:03 connection._info L0250 INFO | [ixn-otg] Count 7
06:42:15 connection._info L0250 INFO | [ixn-otg] Count 8
06:42:28 connection._info L0250 INFO | [ixn-otg] Count 9
06:42:41 connection._info L0250 INFO | [ixn-otg] Count 10
06:42:53 connection._info L0250 INFO | [ixn-otg] Count 11
06:43:06 connection._info L0250 INFO | [ixn-otg] Count 12
06:43:19 connection._info L0250 INFO | [ixn-otg] Count 13
06:43:31 connection._info L0250 INFO | [ixn-otg] Count 14
06:43:44 connection._info L0250 INFO | [ixn-otg] Count 15
06:43:57 connection._info L0250 INFO | [ixn-otg] Count 16
06:44:09 connection._info L0250 INFO | [ixn-otg] Count 17
06:44:22 connection._info L0250 INFO | [ixn-otg] Count 18
06:44:35 connection._info L0250 INFO | [ixn-otg] Count 19
06:44:47 connection._info L0250 INFO | [ixn-otg] Count 20
06:45:00 connection._info L0250 INFO | [ixn-otg] Count 21

**Comment by ashutshkumr** [comment]
@ANISH-GOTTAPU @selldinesh please provide further updates here.
