### ISSUE TITLE
Convergence stats not working as expected for multiple traffic items

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#444]
Below is the snippet

    flow_names = ["IPv4_1-IPv4_2","IPv6_2-IPv6_1","IPv4_1-T1","IPv6_2-T1","T1-IPv4_1"]
    request = cvg_api.convergence_request()
    for i in flow_names:
        request.convergence.flow_names = [i]
        convergence_metrics = cvg_api.get_results(request).flow_convergence
        for metrics in convergence_metrics:
            logger.info('DP/DP Convergence Time (ms) of {} : {}'.format(i,metrics.data_plane_convergence_us/1000))
    #pdb.set_trace()

What seems to happen is; after every iteration in the for loop, it always returns the convergence stats of the first traffic item i.e for "IPv4_1-IPv4_2", it never return the convergence stats of the subsequent traffic items given in the flow_names list

**Comment by alakendu** [comment]
Fix should available >= snappi[ixnetwork,convergence]==0.5.10
