### ISSUE TITLE
Unable to get proper traffic items stats for multiple traffic items

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#445]
Below is the snippet, where im trying to fetch tx ,rx frame rate for 5 traffic items, for first 2 traffic items i am able to get the stats, but for other traffic items im getting rates 0.0, but in GUI its not 0.0

    cs.transmit.flow_names =["IPv4_1-IPv4_2","IPv6_2-IPv6_1","IPv4_1-T1","IPv6_2-T1","T1-IPv4_1"]
    for j,i in enumerate(cs.transmit.flow_names):
        request.metrics.flow_names = [i]
        flow=cvg_api.get_results(request).flow_metric
        logger.info("%s %s %s "%(i,str(flow[0].frames_tx_rate),str(flow[0].frames_rx_rate)))
        assert flow[0].frames_tx_rate == flow[0].frames_tx_rate, "Loss observed for Traffic Item: {}".format(i)
        logger.info("No Loss Observed in Traffic Item {}".format(i))

**output:**
03:43:48 reboot_helper1.get_convergence_for_reboo L0299 INFO   | IPv4_1-IPv4_2 5986.627 5986.627 
03:43:48 reboot_helper1.get_convergence_for_reboo L0301 INFO   | No Loss Observed in Traffic Item IPv4_1-IPv4_2
03:44:22 reboot_helper1.get_convergence_for_reboo L0299 INFO   | IPv6_2-IPv6_1 5986.606 5986.606 
03:44:22 reboot_helper1.get_convergence_for_reboo L0301 INFO   | No Loss Observed in Traffic Item IPv6_2-IPv6_1
03:44:34 reboot_helper1.get_convergence_for_reboo L0299 INFO   | IPv4_1-T1 0.0 0.0 
03:44:34 reboot_helper1.get_convergence_for_reboo L0301 INFO   | No Loss Observed in Traffic Item IPv4_1-T1
03:44:47 reboot_helper1.get_convergence_for_reboo L0299 INFO   | IPv6_2-T1 0.0 0.0 
03:44:47 reboot_helper1.get_convergence_for_reboo L0301 INFO   | No Loss Observed in Traffic Item IPv6_2-T1
03:44:59 reboot_helper1.get_convergence_for_reboo L0299 INFO   | T1-IPv4_1 0.0 0.0 
03:44:59 reboot_helper1.get_convergence_for_reboo L0301 INFO   | No Loss Observed in Traffic Item T1-IPv4_1

**Comment by alakendu** [comment]
Fix should available >= snappi[ixnetwork,convergence]==0.5.10
