### ISSUE TITLE
Restart Down of protocol support is needed

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#456]
**Is your feature request related to a use case? Please describe.**
In case of BGP scalability test , we are incrementing the route count say 16000, 17000, and so on, when the routes are higher sometimes the IPv4 and v6 sessions down come up at all after starting traffic using snappi, as a workaround when we manually do restart down of the protocols, they come up, but there is no way in snappi to do this restart down operation

**Comment by ANISH-GOTTAPU** [comment]
closing this as this is stale issue, please re-open if you want to track this
