### ISSUE TITLE
Start Protocols and Start Traffic operation must be isolated

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#457]
**Is your feature request related to a use case? Please describe.**

In case of BGP scalability we run one test after the other by incrementing the routes, once we reach higher route range say 8k above often time what happens is the IPv4 and V6 sessions doesn't  come up due to which  traffic apply fails and script terminates.
Manually we can bypass this failure by doing the following steps

**Steps**:
1.start protocol
2.check for protocol state
3. if still down, then do a restart down ( this feature is not currently supported in snappi, raised another request for this) or from DUT side you can do a fast reboot to resolve it
4. if all are up proceed to traffic apply

But in current snappi version since protocol and traffic starts at once back to back , there is no way to enforce **Step 2 and 3** chronologically.

If a solution can be provided for this issue, that would be helpful.

**Comment by ANISH-GOTTAPU** [comment]
@selldinesh : The requested feature is available as part of snappi==0.6.x, but ixnetwork implementation is in progress. Please let us know how fast you want this feature

@ashutshkumr : FYI

**Comment by selldinesh** [comment]
The sooner the better, this is needed along with restart down support.
These 2 support is needed for the test gap coverage cases to be implemented

**Comment by alakendu** [comment]
This should address in https://github.com/open-traffic-generator/snappi/releases/tag/v0.7.3
