### ISSUE TITLE
Support for vxlan and Nested devices

### ISSUE THREAD

**Issue by vkuma82** [open-traffic-generator/snappi-ixnetwork#459]
**Is your feature request related to a use case? Please describe.**
BGP over EVPN VxLAN VxLan

**Describe the solution you'd like**
Need support in snapi for VxLan and adding chained device groups

**Describe alternatives you've considered**
RestPy

**Additional context**
We want to create below shown config.
![BGP_EVPNVxLAN](https://user-images.githubusercontent.com/21184819/145081969-b784531e-a9a5-4ec0-8696-8c31bd53a965.PNG)
.

**Comment by ANISH-GOTTAPU** [comment]
Support is available in snappi[ixnetwork]==0.7.44
