### ISSUE TITLE
Getting E could not convert string to float: for convergence_metrics = cvg_api.get_results(request).flow_convergence

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#460]
Getting the below error while running in linux api server, but in windows version its working fine

22:12:17 __init__.pytest_runtest_call             L0039 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/var/johnar/sonic-mgmt/tests/snappi/bgp/test_bgp_remote_link_failover.py", line 63, in test_bgp_convergence_for_remote_link_failover
    port_speed,)
  File "/var/johnar/sonic-mgmt/tests/snappi/bgp/files/bgp_convergence_helper.py", line 108, in run_bgp_remote_link_failover_test
    route_type,)
  File "/var/johnar/sonic-mgmt/tests/snappi/bgp/files/bgp_convergence_helper.py", line 587, in get_convergence_for_remote_link_failover
    table.append(get_avg_cpdp_convergence_time(route))
  File "/var/johnar/sonic-mgmt/tests/snappi/bgp/files/bgp_convergence_helper.py", line 567, in get_avg_cpdp_convergence_time
    convergence_metrics = cvg_api.get_results(request).flow_convergence
  File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 168, in get_results
    raise SnappiIxnException(err)
SnappiIxnException:   File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 152, in get_results
    response = self._result(payload.convergence)
  File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 294, in _result
    -1
 could not convert string to float: 

----------------------------------------------------------- live log teardown -----------------------------------------------------------
22:12:17 __init__._fixture_generator_decorator    L0082 INFO   | -------------------- fixture cvg_api teardown starts --------------------
22:12:17 __init__._fixture_generator_decorator    L0091 INFO   | -------------------- fixture cvg_api teardown ends --------------------
22:12:17 __init__._fixture_generator_decorator    L0082 INFO   | -------------------- fixture start_pfcwd_after_test teardown starts --------------------
22:12:19 __init__._fixture_generator_decorator    L0091 INFO   | -------------------- fixture start_pfcwd_after_test teardown ends --------------------
22:12:19 __init__._fixture_generator_decorator    L0082 INFO   | -------------------- fixture rand_lossy_prio teardown starts --------------------
22:12:19 __init__._fixture_generator_decorator    L0091 INFO   | -------------------- fixture rand_lossy_prio teardown ends --------------------
22:12:19 __init__._fixture_generator_decorator    L0082 INFO   | -------------------- fixture rand_lossless_prio teardown starts --------------------
22:12:19 __init__._fixture_generator_decorator    L0091 INFO   | -------------------- fixture rand_lossless_prio teardown ends --------------------
22:12:19 __init__._fixture_generator_decorator    L0082 INFO   | -------------------- fixture enable_packet_aging_after_test teardown starts --------------------
22:12:19 __init__._fixture_generator_decorator    L0091 INFO   | -------------------- fixture enable_packet_aging_after_test teardown ends --------------------

=============================================================== FAILURES ================================================================
______________________________ test_bgp_convergence_for_remote_link_failover[speed_400_gbps-IPv4-1000-1-7] ______________________________

cvg_api = <snappi_ixnetwork.snappi_convergence_api.Api object at 0x7f31c6cd9e50>, duthost = <MultiAsicSonicHost> sonic-s6100-dut
tgen_ports = [{'card_id': '1', 'ip': '28.1.1.2', 'ipv6': '2000:8::7c95:db9c:b935:8906', 'ipv6_prefix': '64', ...}, {'card_id': '1',...x': '64', ...}, {'card_id': '1', 'ip': '27.1.1.2', 'ipv6': '2000:7::5c31:798:63b:34ca', 'ipv6_prefix': '64', ...}, ...]
conn_graph_facts = {'device_conn': {'sonic-s6100-dut': {'Ethernet160': {'peerdevice': u'ixia-sonic', 'peerport': u'Card1/Port1', 'speed':...-dut': {'CardType': u'Linecard', 'HwSku': u'Accton-AS9716-32D', 'HwSkuType': u'predefined', 'Type': u'DevSonic'}}, ...}
fanout_graph_facts = {u'ixia-sonic': {'device_conn': {'Card1/Port1': {'peerdevice': u'sonic-s6100-dut', 'peerport': u'Ethernet160', 'speed'...rdType': u'Linecard', 'HwSku': u'IXIA-tester', 'HwSkuType': u'predefined', 'ManagementGw': u'10.36.79.207', ...}, ...}}
multipath = 7, convergence_test_iterations = 1, number_of_routes = 1000, route_type = 'IPv4', port_speed = 'speed_400_gbps'

    @pytest.mark.parametrize('multipath',[7])
    @pytest.mark.parametrize('convergence_test_iterations',[1])
    @pytest.mark.parametrize('number_of_routes',[1000])
    @pytest.mark.parametrize('route_type',['IPv4'])
    @pytest.mark.parametrize('port_speed',["speed_400_gbps"])
    def test_bgp_convergence_for_remote_link_failover(cvg_api,
                                                      duthost,
                                                      tgen_ports,
                                                      conn_graph_facts,
                                                      fanout_graph_facts,
                                                      multipath,
                                                      convergence_test_iterations,
                                                      number_of_routes,
                                                      route_type,
                                                      port_speed,):
    
        """
        Topo:
        TGEN1 --- DUT --- TGEN(2..N)
    
        Steps:
        1) Create BGP config on DUT and TGEN respectively
        2) Create a flow from TGEN1 to (N-1) TGEN ports
        3) Send Traffic from TGEN1 to (N-1) TGEN ports having the same route range
        4) Simulate route withdraw from one of the (N-1) BGP peers which is the equivalent of remote link failure
        5) Calculate the cp/dp for convergence time
        6) Clean up the BGP config on the dut
    
        Verification:
        1) Send traffic with all routes advertised by BGP peers
            Result: Should not observe traffic loss
        2) Withdraw all routes from one of the BGP peer
            Result: The traffic must be routed via rest of the ECMP paths and should not observe traffic loss
    
        Args:
            snappi_api (pytest fixture): Snappi API
            duthost (pytest fixture): duthost fixture
            tgen_ports (pytest fixture): Ports mapping info of testbed
            conn_graph_facts (pytest fixture): connection graph
            fanout_graph_facts (pytest fixture): fanout graph
            multipath: ECMP value
            convergence_test_iterations: number of iterations the cp/dp convergence test has to be run for a port
            number_of_routes:  Number of IPv4/IPv6 Routes
            route_type: IPv4 or IPv6 routes
            port_speed: speed of the port used for test
        """
        #convergence_test_iterations, multipath, number_of_routes and route_type parameters can be modified as per user preference
        run_bgp_remote_link_failover_test(cvg_api,
                                          duthost,
                                          tgen_ports,
                                          convergence_test_iterations,
                                          multipath,
                                          number_of_routes,
                                          route_type,
>                                         port_speed,)

conn_graph_facts = {'device_conn': {'sonic-s6100-dut': {'Ethernet160': {'peerdevice': u'ixia-sonic', 'peerport': u'Card1/Port1', 'speed':...-dut': {'CardType': u'Linecard', 'HwSku': u'Accton-AS9716-32D', 'HwSkuType': u'predefined', 'Type': u'DevSonic'}}, ...}
convergence_test_iterations = 1
cvg_api    = <snappi_ixnetwork.snappi_convergence_api.Api object at 0x7f31c6cd9e50>
duthost    = <MultiAsicSonicHost> sonic-s6100-dut
fanout_graph_facts = {u'ixia-sonic': {'device_conn': {'Card1/Port1': {'peerdevice': u'sonic-s6100-dut', 'peerport': u'Ethernet160', 'speed'...rdType': u'Linecard', 'HwSku': u'IXIA-tester', 'HwSkuType': u'predefined', 'ManagementGw': u'10.36.79.207', ...}, ...}}
multipath  = 7
number_of_routes = 1000
port_speed = 'speed_400_gbps'
route_type = 'IPv4'
tgen_ports = [{'card_id': '1', 'ip': '28.1.1.2', 'ipv6': '2000:8::7c95:db9c:b935:8906', 'ipv6_prefix': '64', ...}, {'card_id': '1',...x': '64', ...}, {'card_id': '1', 'ip': '27.1.1.2', 'ipv6': '2000:7::5c31:798:63b:34ca', 'ipv6_prefix': '64', ...}, ...]

snappi/bgp/test_bgp_remote_link_failover.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
snappi/bgp/files/bgp_convergence_helper.py:108: in run_bgp_remote_link_failover_test
    route_type,)
snappi/bgp/files/bgp_convergence_helper.py:587: in get_convergence_for_remote_link_failover
    table.append(get_avg_cpdp_convergence_time(route))
snappi/bgp/files/bgp_convergence_helper.py:567: in get_avg_cpdp_convergence_time
    convergence_metrics = cvg_api.get_results(request).flow_convergence
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <snappi_ixnetwork.snappi_convergence_api.Api object at 0x7f31c6cd9e50>
payload = <snappi_convergence.snappi_convergence.ConvergenceRequest object at 0x7f31c5748290>

    def get_results(self, payload):
        try:
            self._api._connect()
            cvg_req = self.convergence_request()
            if isinstance(payload, (type(cvg_req), str)) is False:
                raise TypeError(
                    "The content must be of type Union[MetricsRequest, str]"
                )
            if isinstance(payload, str) is True:
                payload = cvg_req.deserialize(payload)
            if payload.choice is None:
                raise Exception("state [metrics/ convergence] must configure")
            cvg_res = self.convergence_response()
            if payload.choice == "metrics":
                response = self._api.traffic_item.results(payload.metrics)
                cvg_res.flow_metric.deserialize(response)
            elif payload.choice == "convergence":
                response = self._result(payload.convergence)
                cvg_res.flow_convergence.deserialize(response)
            elif (
                payload.choice
                in self._api.protocol_metrics.get_supported_protocols()
            ):
                response = self._api.protocol_metrics.results(payload)
                getattr(cvg_res, payload.choice + "_metrics").deserialize(
                    response
                )
            else:
                raise Exception(
                    "These[metrics/ convergence] are valid convergence_request"
                )
            return cvg_res
        except Exception as err:
>           raise SnappiIxnException(err)
E           SnappiIxnException:   File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 152, in get_results
E               response = self._result(payload.convergence)
E             File "/var/johnar/.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 294, in _result
E               -1
E            could not convert string to float:

cvg_req    = <snappi_convergence.snappi_convergence.ConvergenceRequest object at 0x7f31c5748050>
cvg_res    = <snappi_convergence.snappi_convergence.ConvergenceResponse object at 0x7f31c57485f0>
err        = ValueError('could not convert string to float: ',)
payload    = <snappi_convergence.snappi_convergence.ConvergenceRequest object at 0x7f31c5748290>
self       = <snappi_ixnetwork.snappi_convergence_api.Api object at 0x7f31c6cd9e50>

../../.local/lib/python2.7/site-packages/snappi_ixnetwork/snappi_convergence_api.py:168: SnappiIxnException
=========================================================== warnings summary ============================================================
/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py:538
  /usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py:538: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: tests.common.dualtor
    self.import_plugin(import_spec)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
-------------------------------------------------------- live log sessionfinish ---------------------------------------------------------
22:12:19 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
=========================== short test summary info ============================
FAILED snappi/bgp/test_bgp_remote_link_failover.py::test_bgp_convergence_for_remote_link_failover[speed_400_gbps-IPv4-1000-1-7]
==================== 1 failed, 1 warnings in 306.80 seconds ====================
INFO:root:Can not get Allure report URL. Please check logs

**Comment by selldinesh** [comment]
In 9.20 latest versions , In case of LAG, the event name for route withdraw operation does not require drill down operation. If we do drill down operation to show physical ports the event name doesn't come. Due to which the BGP remote link failover case is failing

**Comment by ANISH-GOTTAPU** [comment]
As discussed, I will add a check for ixnetwork version to drilldown on LAG for Versions below 9.20 else don't drill down on LAG

**Comment by ANISH-GOTTAPU** [comment]
As this is breaking change from ixNetwork, can you check with the engineer and let the usecase why the event name moved from drilldown to LAG
