### ISSUE TITLE
[0.5.14] Per flow stats need a more reliable way to determine traffic is stopped

### ISSUE THREAD

**Issue by dgalan-xxia** [open-traffic-generator/snappi-ixnetwork#482]
**Version information**
0.5.14

**Describe the bug**
Using `api._enable_flow_tracking(True)` to get flow stats instead of traffic stats (we create a single traffic item fully meshed between 16 ports). `transmit` flow metrics does not show as stopped. 
This is because, according to @ANISH-GOTTAPU, "Snappi-ixnetwork uses "Tx Frame Rate" from flow stats (CSV Snapshot) to validate the flow state as started/stopped. The Snapshot is not reflecting the actual stats shown in UI if the TotalRows on the page are greater than  50."
This is not a reliable way of determining if traffic is stopped. Suggesting to use `isTrafficRunning `attribute of Traffic

**To Reproduce**
https://keysight.slack.com/archives/C01LHDYML9Y/p1637800583038600

**Expected behavior**
https://keysight.slack.com/archives/C01LHDYML9Y/p1637800583038600

**Additional context**

[RE CSV snapshot issue for flow statistics (TotalRows  50).zip](https://github.com/open-traffic-generator/snappi-ixnetwork/files/8119287/RE.CSV.snapshot.issue.for.flow.statistics.TotalRows.50.zip)

**Comment by ANISH-GOTTAPU** [comment]
This doesn't fit for all the usecase, if we have a combination of fixed flows and continuous flows then the traffic will be always in running state. AFAIK `isTrafficRunning` check is at the global level for all traffic but not per flow.
