### ISSUE TITLE
Support for loopback

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi-ixnetwork#493]
**Is your feature request related to a use case? Please describe.**
OTG model have support array of loopbcak interface which connected to a unique ethernet.

**Describe the solution you'd like**
- Create a Device Group (DG) with loopback and connected directly to the ethernet.
- Add a provision to add supported protocol on top of loopback
- We need internal map to set endpoint and protocols

**Describe alternatives you've considered**
We also have a option to connect to network group (NG). But that will require more knowledge to map proper NG

**Additional context**
Nil

**Comment by ANISH-GOTTAPU** [comment]
Merged with #500
