### ISSUE TITLE
Need support to change Media type in l1 settings for ports

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#505]
Need snappi support to change media type as [copper,fibre,sgmii] options
![image](https://user-images.githubusercontent.com/40899231/159333526-5d780b92-bfe2-438f-b08f-0ce0af1095e6.png)

Currently I don't find such support in the sample scripts
This is having high priority for running scripts on dent which has fibre optics connected to it

**Comment by ANISH-GOTTAPU** [comment]
option is available

Ex: 
https://github.com/open-traffic-generator/snappi-ixnetwork/issues/462
