### ISSUE TITLE
Model BGP and Route Range ( IPv4 and IPv6 Ranges ) - as well as route parameter like Metric

### ISSUE THREAD

**Issue by SubhajitPalKeysight** [open-traffic-generator/snappi-ixnetwork#56]
Model Routes - Adv / Withdraw Routes

Model To get these Result ( BGP Sessions from Protocol stat ) and Next ( BGP Route Adv/Withdraw msg cout )

**Comment by ANISH-GOTTAPU** [comment]
Implementation done
