### ISSUE TITLE
All L1 configs are not being seen for the card XM100GE4qsfp28+ENH+25G+50G

### ISSUE THREAD

**Issue by anushvarada** [open-traffic-generator/snappi-ixnetwork#567]
**Version information**
0.9.1
                                                
![image](https://github.com/open-traffic-generator/snappi-ixnetwork/assets/12361356/7b79976d-25f1-4f4f-8160-55123f7378b0)
![image](https://github.com/open-traffic-generator/snappi-ixnetwork/assets/12361356/749dc580-c36a-4e57-96f0-1983fc2ace89)

Local Fix given in customer environment, please apply the same in our main release.

**Comment by indraniBh** [comment]
Fix available in v1.17.0.
