### ISSUE TITLE
AttributeError: 'Api' object has no attribute 'protocol_state'

### ISSUE THREAD

**Issue by Praveena46** [open-traffic-generator/snappi-ixnetwork#572]
**Version information**
The pypi version or branch of snappi-ixnetwork

**Describe the bug**
I am trying to i=open the IxNetwork API  by using Snappi-Ixnetwork  and while confighuring the endpoint getting the atribuite error
Traceback (most recent call last):
  File "C:\WS\myproject\idea\S32\.venv\lib\site-packages\snappi\snappi.py", line 103, in api
    return lib.Api(**params)
  File "C:\WS\myproject\snappi-ixnetwork\snappi_ixnetwork\snappi_api.py", line 70, in __init__
    self._protocol_state = self.protocol_state()
AttributeError: 'Api' object has no attribute 'protocol_state'

**To Reproduce**
Steps to reproduce the behavior. Prefer code snippets, pytest test cases.
import snappi
# host is IxNetwork API Server
#api = snappi.api(location='https://localhost:443', ext='ixnetwork')
api = snappi.api(location='https://localhost:20320', ext='ixnetwork')

**Expected behavior**

I want to open the ixnetwork API while running the code

**Additional context**
Add any other context about the problem her

**Comment by indraniBh** [comment]
Issue is fixed in snappi-ixnetwork v1.13.0.
It incorporates support of new APIs.
`protocol_state` is obsolete in OTG model 1.x onwards.
Sample new api:
```
# start transmitting configured flows
control_state = api.control_state()
control_state.choice = control_state.TRAFFIC
control_state.traffic.choice = control_state.traffic.FLOW_TRANSMIT
control_state.traffic.flow_transmit.state = control_state.traffic.flow_transmit.START  # noqa
api.set_control_state(control_state)
```
