### ISSUE TITLE
cannot set same name for different type of objects

### ISSUE THREAD

**Issue by ByReaL** [open-traffic-generator/snappi-ixnetwork#66]
if I try to have the port named W-01 and the device named W-01 we will get a validation error

```
C:\Python37x86\Lib\site-packages\ixnetwork_open_traffic_generator\validation.py
__check_config_objects
```
this line seems to create a problem
`if attr_value in self._api._config_objects:`

it should verify only for objects of the same type, no duplicate name for ports, no duplicate names for devices, but naming a port and a device and a bgp and an ipv4 same it should not be a violation.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, division, unicode_literals

# test configuration area ******************************************************************
if 'py' not in dir():
    class Py:
        pass
    py = Py()
    py.ports = ['localuhd/%d'% port for port in range(1,33)]
    py.server = '10.36.70.75'
# ******************************************************************************************

import json
import time

from tabulate import tabulate

import abstract_open_traffic_generator as aotg
import abstract_open_traffic_generator.port
import abstract_open_traffic_generator.config
import abstract_open_traffic_generator.device
import abstract_open_traffic_generator.control
from ixnetwork_open_traffic_generator.ixnetworkapi import IxNetworkApi
print(py.ports)

print('connect to the test tool platform')
api = IxNetworkApi(address=py.server, port=443)

print('closing all existing sessions - implement me')
#test_platform.Sessions.find().remove()

print('building the config')
config = aotg.config.Config()

for i in range(1,len(py.ports)+1):
    print(i)
    pname = '%s-%02d' % ('E' if i % 2 == 0 else 'W', (i+1)//2)
    print(pname)
    port = aotg.port.Port(name=pname, location='localuhd/%d' % i)
    config.ports.append(port)

    nd_digit = i//2
    ip_digit = 1 if i % 2 == 0 else 2
    gw_digit = 2 if i % 2 == 0 else 1

    config.devices.append(
        aotg.device.Device(
            name = pname,
            container_name = port.name,
            device_count = 1,
            choice = aotg.device.Ipv4(
                name = 'ipv4-%d' % i,
                address = aotg.device.Pattern('180.%d.0.%d' % (nd_digit, ip_digit)),
                prefix = aotg.device.Pattern('24'),
                gateway = aotg.device.Pattern('180.%d.0.%d' % (nd_digit, gw_digit)),
            )
        )
    )

print('loading the config')
api.set_state(aotg.control.State(aotg.control.ConfigState(config=config, state='set')))
```

_Traceback (most recent call last):
  File "/regression/tgen/tgen.self.py", line 70, in <module>
    api.set_state(aotg.control.State(aotg.control.ConfigState(config=config, state='set')))
  File "/usr/lib/python3.8/site-packages/ixnetwork_open_traffic_generator/ixnetworkapi.py", line 92, in set_state
    self._set_config_state(state.config_state)
  File "/usr/lib/python3.8/site-packages/ixnetwork_open_traffic_generator/ixnetworkapi.py", line 106, in _set_config_state
    self.validation.validate_config()
  File "/usr/lib/python3.8/site-packages/ixnetwork_open_traffic_generator/validation.py", line 20, in validate_config
    raise NameError(', '.join(self._unique_name_errors))
NameError: Port.name: "W-01" is not unique, Port.name: "E-01" is not unique, Port.name: "W-02" is not unique, Port.name: "E-02" is not unique, Port.name: "W-03" is not unique, Port.name: "E-03" is not unique, Port.name: "W-04" is not unique, Port.name: "E-04" is not unique, Port.name: "W-05" is not unique, Port.name: "E-05" is not unique, Port.name: "W-06" is not unique, Port.name: "E-06" is not unique, Port.name: "W-07" is not unique, Port.name: "E-07" is not unique, Port.name: "W-08" is not unique, Port.name: "E-08" is not unique, Port.name: "W-09" is not unique, Port.name: "E-09" is not unique, Port.name: "W-10" is not unique, Port.name: "E-10" is not unique, Port.name: "W-11" is not unique, Port.name: "E-11" is not unique, Port.name: "W-12" is not unique, Port.name: "E-12" is not unique, Port.name: "W-13" is not unique, Port.name: "E-13" is not unique, Port.name: "W-14" is not unique, Port.name: "E-14" is not unique, Port.name: "W-15" is not unique, Port.name: "E-15" is not unique, Port.name: "W-16" is not unique, Port.name: "E-16" is not unique_

**Comment by ashutshkumr** [comment]
@ajbalogh @alakendu what do you guys think ? should we make the names unique based on the object type ?

**Comment by ajbalogh** [comment]
This is based on the openapi name property description that dictates name is "Globally unique name of an object. It also serves as the primary key for arrays of objects."
I would recommend leaving the name as globally unique.

**Comment by ANISH-GOTTAPU** [comment]
stale issue
