### ISSUE TITLE
Add test for IPv4 header with varying header and packet length

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi-ixnetwork#90]
- Add new test script inside tests/ipv4/
- Create multiple flows each with 64B, 128B and 1518B frame sizes
- Add one more flow of any size, containing IPv4 extension header (so that header lenght is not the default one). Custom header can be added as a custom byte sequence.
- Validate that header_length, total_length and header_checksum fields are correct from captured frame

**Comment by ANISH-GOTTAPU** [comment]
test added
